py ACTOR_PELICULA/app1.py "Ivan" "Mariana" "LA VIDA ES BELLA"
py AUTOR_OBRA/app2.py "Paco Yunque" "Trilce" "Cesar Vallejo"
py BICICLETA_LLANTA/app3.py "Fibra de carbono" "50" "BMX"
py BILLETERA_DINERO/app4.py "cuero" 40 "sport" "S/."
py CABALLO_JINETE/app6.py "Paint Horse" "Arturo" "sangre Fria"
py CALULAR_CAMARA/app25.py "Android 9" "48 MP" "15 efectos fotograficos"
py CARRETA_BURRO/app5.py "Pantesco" " cuadrada " "madera"
py CASA_HABITACION/app8.py " Manzana 3" "8 personas" " material noble"
py COLEGIO_ESTUDIANTE/app9.py "Mario" "publico" "JOSE CARLOS MARIATEGUI" "cuarto secc"
py CUENTA_CLIENTE/app10.py "Carlos" "cuenta corriente" " el banco de la nacion"
py CURSO_ALUMNO/app11.py  "Programacion II" " Alexis" "la Universidad"
py EMPRESA_TRABAJADOR/app13.py "La Molinera" "capataz" "8 h/d" 3500
py ESENARIO_CANTANTE/app7.py "El sanjuanero" "zona VIP" "1500 personas" "cumbias"
py ESTADIO_FUTBOL/app14.py "sub-23" "S. Bernabeu" "Madrid"
py HOSPITAL_DOCTOR/app15.py " Perez" "Regional"
py LAPTOP_IMPRESORA/app16.py "300 dpi" " JP-100"
py MOTOR_MOTO/app17.py "una mototaxi" 200 "gasolina de 90"
py NACION_BANDERA/app18.py "2 colores" "Peru"
py OBRERO_PALANA/app20.py "Juan" "hierro"
py PAIS_CIUDAD/app19.py  "Francia" "Paris" "el frances"
py PARED_VENTANA/app21.py "vidrio" "circular" "de una casa"
py PERSONA_PERRO/app22.py "Boby" "Pastor aleman" "Carlos"
py TANQUE_AGUA/app23.py "H2O" "plastico" "2000 lts"
py UNIVERSIDAD_DOCENTE/app12.py "Martin" "nacional" "Pedro Ruiz Gallo"
py VECTOR_PUNTO/app24.py "(1,3)" "unitario" "53 grados"